### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/P-NP#1]
Oh noes prodigy iznt working!!?!? ;(( :))) ;((
Please fix bhgalalsjfhejqa

sent from my iPhone:tm:

**Comment by ArcerionDev** [comment]
lmao mustan

**Comment by bmoser05** [comment]
> Oh noes prodigy iznt working!!?!? ;(( :))) ;((
> Please fix bhgalalsjfhejqa
> 
> sent from my iPhone™️

prodigy isn't loading for me when I have the PHEx Extension if it might be related

**Comment by BoredFishRE** [comment]
it's a joke...
