### ISSUE TITLE
Prodigy keeps loading half way when I use the extension

### ISSUE THREAD

**Issue by achen2341** [Prodigy-Hacking/P-NP#2]
***Description***:
The extension keeps loading half when I try to log in prodigy

***Replication***:

***Images***:
Here is the console

![image](https://user-images.githubusercontent.com/81065431/111909994-e2543000-8a35-11eb-808d-69790ea87e39.png)

***Additional Errors***:

**Comment by NX721** [comment]
Try restarting your device @achen2341 
If you're using a school device and your device has an extension called: "AdBlocker" then we can't help.

**Comment by ArcerionDev** [comment]
already figured it out dw

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/111911377-bfc51580-8a3b-11eb-95d4-681cdfe9458c.png)
es6 operators don't work in browser

**Comment by ArcerionDev** [comment]
fixed now
